### ISSUE TITLE
Large error for preterm babies plotted at 2 y and 1y

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#126]
issue posted on behalf of @statist7 
I've now been able to compare LMSgrowth with RCPCHgrowth and it throws up genuine errors! There are 16 entries where the sds discrepancy exceeds 0.005.

They are for four very preterm children aged >2 whose corrected ages are <2. So the preterm not the term reference should be used.

**Comment by eatyourpeas** [comment]
@statist7 could you post here the the 16 entries for me to reproduce? If you have the calculated corrected ages that would be helpful also.

**Comment by statist7** [comment]
These are the results for the 16 measurements.

![Screenshot 2021-01-22 at 10 19 45](https://user-images.githubusercontent.com/5055653/105478708-6ccd1d00-5c9b-11eb-8b30-a96bc5d3ef75.png)

RCPCH uses the term_sds while LMSgrowth uses the preterm_sds. I think the preterm is correct based on the uncorrected and corrected ages.

Note that the check columns compare rcpch and lms. There is a tiny loss of accuracy for BMI.

**Comment by statist7** [comment]
The discrepancies above for 4 very preterm children arise because RCPCH uses postnatal age while LMS uses corrected age to test at the 2-year cut-off.

I've checked the dataset of 1000 subjects and there are no preterm children with gestation 32+ weeks, postnatal age >1 year and corrected age <1 year, i.e. the equivalent group to the above at the 1-year cut-off. So I'll need to create a couple.

**Comment by statist7** [comment]
If you go to line 391 of the RCPCHgrowth spreadsheet you'll find a boy of 29 weeks gestation, length 76.1 cm and length z-score 0.54. His postnatal age is 1.14 and his corrected age is 0.936, and the z-score is correctly the preterm z-score. 

If now you change his gestation to 32 weeks his z-score changes to -0.64, which is the term z-score. But his corrected age is still less than 1, only 0.98.

This shows that at both the 1-year and 2-year cut-offs, RCPCH is using uncorrected age not corrected age to decide which reference to use.

On 23 October I sent Charlotte an email saying: 

> V quick question – what are the gestations below which one adjusts for age until corrected age reaches 1 and 2 years?

and her reply was: 

> The chart group agreed 32-36 weeks to one year corrected age and <32 weeks to 2 years corrected age

Note - _corrected_ age

**Comment by statist7** [comment]
Having said all that, I do wonder if we should lean on Charlotte to alter the definition. It's easy for everyone to know when a child reaches 1 or 2 years postnatal age, but much less easy to know about their corrected age.

@magdaumerska Perhaps we should raise at the project board next week?

**Comment by eatyourpeas** [comment]
That is very helpful analysis thank you @statist7. Changing from chronological to corrected decimal age at 1 and 2y is a very simple change in terms of the code. I would be happy to make the change if we get rid of chronological age altogether 😉.
Best thing is if I create a new branch and make the change so it is easy to move over if subsequently that is what is decided at project board.

**Comment by eatyourpeas** [comment]
I have made those changes which can be found [here](https://github.com/rcpch/digital-growth-charts-server/blob/age-correction/rcpchgrowth/rcpchgrowth/date_calculations.py), currently in a separate branch. The two functions are below. The corrected_decimal_age function calls the chronological_decimal_age function which calculates the difference between two dates in years. It uses this value as a starting point to correct based on gestation supplied. It now corrects if the corrected age is >= 1y in 32 weeks and above, and >=2y in the very preterm. I have not tested these but if @statist7 you have a small dataset which might include dates I can run some tests to ensure we agree.
```
def chronological_decimal_age(birth_date: date, observation_date: date) -> float:

    """
    Calculates a decimal age from two dates supplied as raw dates without times.
    Returns value floating point
    :param birth_date: date of birth
    :param observation_date: date observation made
    """

    days_between = observation_date - birth_date
    chronological_decimal_age = days_between.days / 365.25
    return chronological_decimal_age
```

```
def corrected_decimal_age(birth_date: date, observation_date: date, gestation_weeks: int, gestation_days: int)->float: 
    """
    Corrects for gestational age. 
    Corrects for 1 year corrected age, if gestation at birth >= 32 weeks and < 37 weeks
    Corrects for 2 years corrected age, if gestation at birth <32 weeks
    Otherwise returns decimal age without correction
    Any baby 37-42 weeks returns decimal age of 0.0
    Depends on chronological_decimal_age
    :param birth_date: date of birth
    :param observation_date: date observation made
    :param gestation_weeks: weeks of gestation up to 40
    :param gestation_days: days in excess of weeks
    """
    
    correction_days = 0
    pregnancy_length_days = TERM_PREGNANCY_LENGTH_DAYS

    if gestation_weeks > 0:
        pregnancy_length_days = (gestation_weeks * 7) + gestation_days

    try:
        uncorrected_age = chronological_decimal_age(birth_date, observation_date)
    except ValueError as err:
        return err


    ## age correction
    prematurity = TERM_PREGNANCY_LENGTH_DAYS - pregnancy_length_days
    correction_days = prematurity
    edd = birth_date + timedelta(days=correction_days)
    corrected_age =  chronological_decimal_age(edd, observation_date)

    if pregnancy_length_days >= TERM_LOWER_THRESHOLD_LENGTH_DAYS:
        #term baby
        return uncorrected_age

    elif pregnancy_length_days < EXTREME_PREMATURITY_THRESHOLD_LENGTH_DAYS and corrected_age <= 2:
        #correct age for 2 years
        return corrected_age

    elif (pregnancy_length_days >= EXTREME_PREMATURITY_THRESHOLD_LENGTH_DAYS) and (pregnancy_length_days < TERM_LOWER_THRESHOLD_LENGTH_DAYS) and uncorrected_age <=1:
        #correct age for 1 year
        return corrected_age
    
    else:
        return uncorrected_age
```

**Comment by magdaumerska** [comment]
Thank you @statist7 and @eatyourpeas - I will flag this matter at the Board meeting on 27.01.2021.

**Comment by statist7** [comment]
Please forgive a couple of comments on the code...

I don't talk Python, but  the lines in `chronological_decimal_age` reading 

`days_between = observation_date - birth_date`
`chronological_decimal_age = days_between.days / 365.25`

look odd to me, with `.days` added to `days_between`. But maybe it's a Python convention that I know nothing about.

And secondly, the `if elif elif else` block can be simplified by handling the most extreme case first, i.e. `if <32 weeks and <2 years elif <37 weeks and <1 year else term`.

**Comment by eatyourpeas** [comment]
The `days_between` is a variable that could be better named perhaps as dates_interval or somesuch.  It is really a datetime object that could be expressed in years, months, days, weeks, hours, minutes, seconds or miliseconds. The `.days` just selects the days from the object.
You are right about the conditional statements I can tidy that up.

**Comment by eatyourpeas** [comment]
This is very helpful feedback @statist7  - thank you for taking the time to look through. Happy to streamline further if you wish. 
```
def chronological_decimal_age(birth_date: date, observation_date: date) -> float:

    """
    Calculates a decimal age from two dates supplied as raw dates without times.
    Returns value floating point
    :param birth_date: date of birth
    :param observation_date: date observation made
    """

    dates_interval = observation_date - birth_date
    chronological_decimal_age = dates_interval.days / 365.25
    return chronological_decimal_age
```
    

```
def corrected_decimal_age(birth_date: date, observation_date: date, gestation_weeks: int, gestation_days: int)->float: 
    """
    Corrects for gestational age. 
    Corrects for 1 year corrected age, if gestation at birth >= 32 weeks and < 37 weeks
    Corrects for 2 years corrected age, if gestation at birth <32 weeks
    Otherwise returns decimal age without correction
    Any baby 37-42 weeks returns decimal age of 0.0
    Depends on chronological_decimal_age
    :param birth_date: date of birth
    :param observation_date: date observation made
    :param gestation_weeks: weeks of gestation up to 40
    :param gestation_days: days in excess of weeks
    """
    
    correction_days = 0
    pregnancy_length_days = TERM_PREGNANCY_LENGTH_DAYS

    if gestation_weeks > 0 and gestation_weeks < 37:
        pregnancy_length_days = (gestation_weeks * 7) + gestation_days

    try:
        uncorrected_age = chronological_decimal_age(birth_date, observation_date)
    except ValueError as err:
        return err


    ## age correction
    correction_days = TERM_PREGNANCY_LENGTH_DAYS - pregnancy_length_days
    edd = birth_date + timedelta(days=correction_days)
    corrected_age =  chronological_decimal_age(edd, observation_date)

    if pregnancy_length_days < EXTREME_PREMATURITY_THRESHOLD_LENGTH_DAYS and corrected_age <= 2:
        #correct age for 2 years
        return corrected_age
    elif (pregnancy_length_days >= EXTREME_PREMATURITY_THRESHOLD_LENGTH_DAYS) and (pregnancy_length_days < TERM_LOWER_THRESHOLD_LENGTH_DAYS) and corrected_age <=1:
        #correct age for 1 year
        return corrected_age
    else:
        return uncorrected_age

```

**Comment by statist7** [comment]
Sorry to labour it, but your `elif` clause is over-complicated. You have already excluded the extremely preterm so it just needs
`elif (pregnancy_length_days < TERM_LOWER_THRESHOLD_LENGTH_DAYS) and corrected_age <= 1:`

**Comment by eatyourpeas** [comment]
Forgive me you are quite right. 
```
def corrected_decimal_age(birth_date: date, observation_date: date, gestation_weeks: int, gestation_days: int)->float: 
    """
    Corrects for gestational age. 
    Corrects for 1 year corrected age, if gestation at birth >= 32 weeks and < 37 weeks
    Corrects for 2 years corrected age, if gestation at birth <32 weeks
    Otherwise returns decimal age without correction
    Any baby 37-42 weeks returns decimal age of 0.0
    Depends on chronological_decimal_age
    :param birth_date: date of birth
    :param observation_date: date observation made
    :param gestation_weeks: weeks of gestation up to 40
    :param gestation_days: days in excess of weeks
    """
    
    correction_days = 0
    pregnancy_length_days = TERM_PREGNANCY_LENGTH_DAYS

    if gestation_weeks > 0 and gestation_weeks < 37:
        pregnancy_length_days = (gestation_weeks * 7) + gestation_days

    try:
        uncorrected_age = chronological_decimal_age(birth_date, observation_date)
    except ValueError as err:
        return err


    ## age correction
    correction_days = TERM_PREGNANCY_LENGTH_DAYS - pregnancy_length_days
    edd = birth_date + timedelta(days=correction_days)
    corrected_age =  chronological_decimal_age(edd, observation_date)

    if pregnancy_length_days < EXTREME_PREMATURITY_THRESHOLD_LENGTH_DAYS and corrected_age <= 2:
        #correct age for 2 years
        return corrected_age
    elif (pregnancy_length_days < TERM_LOWER_THRESHOLD_LENGTH_DAYS) and corrected_age <= 1:
        #correct age for 1 year
        return corrected_age
    else:
        return uncorrected_age
```

**Comment by eatyourpeas** [comment]
This issue is now largely nolonger relevant following project board meeting today where the decision was made to correct for gestational age across the life course. It was suggested that corrected age would be the default representation charts, but that a toggle button might show the chronological ages also. Clarity is needed around term, as to whether age correction continues through 37-42 weeks, and if so what safeguards are in place to prevent concern for babies losing weight in the first 2 weeks of life. I will close this but open new issues.
