### ISSUE TITLE
Do we need the term reference?

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#128]
At project board today the decision was made to correct for gestational age, even when term, across the life course.
This now presents a dilemna with regard to the term reference, which has historically averaged the L, M and S across 37-42 weeks, and used this for all calculations over this time period. Centiles are not rendered over these weeks.

If age is now corrected, it would follow that the UK90 data be reinstated. Safeguards would be needed to make sure physiological weight loss in the first 2 weeks of life is accounted for.

**Comment by eatyourpeas** [comment]
Just to say that commit b5f3cc6cdbdd09ced9fa109e501cb81244915be0 in branch age-correction has removed the term reference. This branch has also removed all code limiting age correction, so this would now happen at any gestation across the life course. This change, if agreed by project board, therefore would also close issue #127.

**Comment by pacharanero** [comment]
Great stuff boss. This really is moving forward the state of the art in growth. Continuous gestational age correction!

**Comment by BB-1313** [comment]
Seconded!

Simon were you surprised?  You didn’t think this was likely last time it came up but it’s definitely a significant technical step forward to remove a convention like that and I’m sure it will simplify analysis and coding in the long run.

Is it worth putting an update on the thread on discourse to begin the necessary raising of awareness?

**Comment by eatyourpeas** [comment]
thank you @BB-1313 yes I was surprised, but I think the project board saw it made sense when they saw the charts we had built. Electronic charting takes all the pain away and protects from human error. Why would you not correct if the computer will do it for you? Though I will still miss those paper charts in a nostalgic kind of way.

**Comment by BB-1313** [comment]
We can have one framed once it’s all done and you can hang it on the wall for posterity!

I noticed your other comment about dealing with acceptable post-natal weight losses but that’s presumably relatively easy to flag at whatever level is conventional alongside the core function of charting/normalising from raw data?

It is also something that is still going to be largely a clinical responsibility to interpret from the chart so hopefully not a major clinical risk either way.

**Comment by pacharanero** [comment]
This is implemented in branch term-references-removed, and once we're happy with testing it will be merged into unstable

**Comment by eatyourpeas** [comment]
This was closed with PR af456e2
