### ISSUE TITLE
Date(Time) Format for API might need to be YYYY-MM-DD”T”HH:MM:SS

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#135]
3.2.8 Looking at the FHIR DateTime it is a full W3C specified, time-zone-aware DateTime such as 2002-10-10T12:00:00-05:00 and I think perhaps we should use that everywhere. In theory it could affect the centile, if a child had been born in one time zone but measured in another, the decimal age could be moved back or forward by one day. @eatyourpeas  

Table 2
I noted the format for DateTime uses full ISO strings YYYY-MM-DD”T”HH:MM:SS. At present the API uses YYYY-MM-DD but we can relatively easily change this and I think it's probably better using the full format. If the time part is not known then presumably we should default to 00:00:00 on the selected date. Time is not taken into account by the centile/SDS calculation whatsoever.

From Table 2 of the DPCHR Spec
> Format of YYYY-MM-DD”T”HH:MM:SS (as per the ‘Date/time’ element from the Event spec)

**Comment by statist7** [comment]
If FHIR needs the time then obviously the API should provide it. But we should be clear that only the date and not the time is used in the calculation.

**Comment by pacharanero** [comment]
Yes, completely agree.

**Comment by pacharanero** [comment]
closed with rcpch/digital-growth-charts-server#151
