### ISSUE TITLE
Updated Privacy Policy 

### ISSUE THREAD

**Issue by magdaumerska** [rcpch/digital-growth-charts-server#141]
Hi @pacharanero - please see the attached updated Privacy Policy for digital growth charts. We now have an EEA Rep, which we need to give details to if we are likely to have any users who are based in the EU and outside the UK. 
Can you please replace this policy on https://dev.rcpch.ac.uk/privacy ? 

Thank you,
Magda 

[Updated Digital Growth Charts Privacy Policy.docx](https://github.com/rcpch/digital-growth-charts-server/files/6162982/Updated.Digital.Growth.Charts.Privacy.Policy.docx)

**Comment by pacharanero** [comment]
I have added the new privacy policy

**Comment by magdaumerska** [comment]
Thank you @pacharanero - I think the updated version is still yet to appear here https://dev.rcpch.ac.uk/privacy (maybe it takes some time) i.e. Our EEA Representative section is still missing.

**Comment by pacharanero** [comment]
Try now. It is up there now
