### ISSUE TITLE
if observation date is BEFORE birth date then an error should be raised

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#157]
at this point we should raise some kind of error - Measurement class instantiation should not proceed

Assignees: @pacharanero,@eatyourpeas
Labels: 

https://github.com/rcpch/digital-growth-charts-server/blob/3345a637425bed25421a79cae5c4f665525c08da/rcpchgrowth/rcpchgrowth/measurement.py#L403-L403

**Comment by eatyourpeas** [comment]
fixed with commit a76b168b47ae71c26be3f2a5c7b2f150fef8a25a
