### ISSUE TITLE
missing corrected_sds value

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#158]
https://github.com/rcpch/digital-growth-charts-server/blob/f82f186f8efe1a0ac4119f112075219422e23217/rcpchgrowth/rcpchgrowth/tests/sds_age_validation_2021.json#L33591-L33591

@statist7 we've been working through issues with the 4000-child test rig, and have found one 'edge case' child in which they have an incalculable chronological SDS for OFC, owing to being a female over 17 years - BUT their corrected age is under 17, which means we can calculate a corrected_sds for them.

We've inserted a random number of 60.001 as the observation data (we had to do this for a number of children who had incalculable SDS for OFC - the missing observation_value was breaking our test)

(This corresponds to line 633 of the source data spreadsheet.)

**Comment by statist7** [comment]
My view is that if either the chronological or adjusted sds is not available then NA should be returned for both. The alternative would be something of a nightmare for the charting code, and switching the view from one to the other would cause the child to appear and disappear.

**Comment by pacharanero** [comment]
Yeah, it's a good point. But implementing that in the code might be tricky since we would have to check that the child has a valid Corrected age for the calculation as well as Chronoloigcal age - BEFORE returning either.
And it might be odd for some users if they see that the corrected age is <17 but there's still no response.
@eatyourpeas any views either way? I'm happy to go with the majority view.

**Comment by eatyourpeas** [comment]
It should be possible in the charts to render the value that is returned in the tool tip for that point, and an error message in the chronological one explaining no reference data

S

**Comment by statist7** [comment]
On further reflection I think we should return NA for both if chronological sds is missing, but if chronological sds is available then it should be returned even if corrected sds is NA. This is because the concept of corrected sds is pretty nebulous at 17-18 years.

**Comment by eatyourpeas** [comment]
Currently the issue arises around OFC at 17y in girls and 18y in boys. It these circumstances the only scenario would be a calculable corrected value and an incalculable chronological one. I guess the reverse could happen at the bottom end of the chart, say where length at 24 weeks could not be plotted but could be at 40+ as a chronological measurement. In those circumstances the preterm comment would flag a no data error. I am not sure chronologically plotted data in preterm infants add that much value but that it is the standard we have.

**Comment by BB-1313** [comment]
Hi guys, I can see great progress being made.
This issue seemed accesible to me!  How about using the final value in the reference data as valid for all higher values of age.
There are some parameters which this would be invalid for but if it's height/OFC/weight, once adult age and size is achieved they could be considered "fixed" even though this is strictly not true although probably is true for the just older than reference ages cases that will liekly result in the problem
I imagine that might be easier to code?  It won't solve the issue of absent reference data for viable gestations at the bottom age of course

**Comment by statist7** [comment]
We can obviously write a long essay on this topic! 

The problem with @BB-1313's suggestion is that for some references, notably weight or BMI, the value keeps rising throughout adulthood, so it makes no sense to extrapolate the value at the oldest reference age to later ages. 

Maybe we should just be pragmatic, and return NA values as and when they arise. So in the example we would return NA for chronological sds and the value for corrected sds. We would need to explain how it can happen, but it would at least be transparent.

**Comment by eatyourpeas** [comment]
closing
