### ISSUE TITLE
Reinstate Fictional Child API Endpoint

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#165]
We have found a use-case where a Synthetic Child Data endpoint might be useful - this is in generating some 'plausible' demo data to plot on the Demo React client, for when we're doing a rapid demo to people. It would do this with a single click, instead of having to enter multiple plots manually. There will be a button in the React Client which will auto-fill a number of plotted points (may be configurable)

This button will call the Synthetic Child Data API endpoint to get dummy data, then it will plot the points.

There used to be a Fictional Child endpoint so it's been done once. We can probably go back in the Git history and bring that endpoint back, but of course the calculation will now be done in the `rcpchgrowth-python` external package.

## Synthetic Child Data API sketch (based on how it used to work)
* start SDS
* end SDS
* number of points to plot
* randomness - the 'scatter' either side of a straight line between Start and End SDS

## Flask Implementation needs
* a Blueprint with relevant Flask code for calling the Python package and openAPI3 specs
* Error handling
* Validation of inputs (can use Marshmallow for this, ie same as the tool for openAPI3 specs)
* Tests which actually call the API
* Documentation

**Comment by eatyourpeas** [comment]
This has now been implemented in the RCPCHGrowth package 2.2.0 so just needs wiring up now.

**Comment by eatyourpeas** [comment]
This is now implemented and functioning as of 2.2.9, with a route in the API and a form in the client
