### ISSUE TITLE
Getting 404 - Resource Not Found exception while calling Mid Parental Height API end point

### ISSUE THREAD

**Issue by princepsivannhs** [rcpch/digital-growth-charts-server#187]
- URL used: https://api.rcpch.ac.uk/growth/v1/utilities/mid-parental-height
- Request type: POST
- Subscription Type: Free Trial
- Request Body:
{
  "height_paternal": 160,
  "height_maternal": 170,
  "sex": "male"
}

- Response:
{
    "statusCode": 404,
    "message": "Resource not found"
}

**Comment by pacharanero** [comment]
Are you including your API key when sending the request?

**Comment by princepsivannhs** [comment]
Yes. We're using the same API key to get UK-WHO centile calculations, and we're getting the calculated centiles as expected for those requests.

**Comment by princepsivannhs** [comment]
Hi team, is there any update on this?

**Comment by pacharanero** [comment]
Hi @princepsivannhs we have located the problem and it should be a relatively easy fix. Hopefully in the next few days.
Are you currently subscribing to one of the paid tiers or on teh free tier? (just for info/outreach etc)

**Comment by princepsivannhs** [comment]
Hi @pacharanero thanks for the update!
We're currently using a free tier as part of developing a growth chart app for Royal Cornwall Hospital.

**Comment by princepsivannhs** [comment]
Hi @pacharanero, hope you're well.
I was wondering if there is any further update on this.

**Comment by pacharanero** [comment]
I have been investigating and will try to fix soon.

**Comment by princepsivannhs** [comment]
Thanks for the update.

**Comment by pacharanero** [comment]
@princepsivannhs thanks for your patience on this, we have fixed this issue today and the midparental height endpoint should now be able to be accessed at https://api.rcpch.ac.uk/growth/v1/utilities/mid-parental-height as in the following example:

```bash
curl --location --request POST 'https://api.rcpch.ac.uk/growth/v1/utilities/mid-parental-height' \
--header 'Subscription-Key: YOUR_API_KEY_HERE' \
--header 'Content-Type: application/json' \
--data-raw '{
    "height_paternal": 182,
    "height_maternal": 176,
    "sex": "male"
}'
{"mid_parental_height":185.5,"mid_parental_height_sds":1.1711200756015423,"mid_parental_height_centile":87.92247423010475,"mid_parental_height_centile_data":[ <LARGE_ARRAY_OF_DATA_POINTS_FOR_PLOTTING_MPH> ... (clipped) ]
```

**Comment by princepsivannhs** [comment]
@pacharanero thank you very much! 

We tried testing this on postman, and looks like everything's working as it should be. We're yet to test this further using our application. I shall reach out to you in case we require any further help/assistance.
Thanks again

Cheers,
Prince
