### ISSUE TITLE
Python Version Upgrade

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#189]
The [Digital Growth Charts Server](https://github.com/rcpch/digital-growth-charts-server) currently targets Python 3.8.

According to https://devguide.python.org/versions/ we should be looking to move to at least 3.10 if not 3.11 and deprecate some older versions.

**Comment by dc2007git** [comment]
This is a matter of priority now that 3.12 is in and 3.8 is on its way out as an active version.

**Comment by pacharanero** [comment]
Some work has been done on this now - we have started to Dockerise the development environment of the API server. Dockerisation makes it very easy to run a different Python version locally with one simple change of the Python version in the Dockerfile.

At the same time we are also updating the GitHub Actions pytest workflows, so as to run a matrix strategy, that tests the code against the full range of actively supported Python versions.

**Comment by pacharanero** [comment]
Closed by #206

**Comment by pacharanero** [comment]
this was closed along with the partner Issue on the rcpch-growth package
