### ISSUE TITLE
Client libraries for the API??

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#19]
A client library is a piece of software that we produce, as the _creators_ of the API which we distribute to _consumers_ of the API. The library allows them to integrate with the API more easily, by providing utility functions in a language that the developer is familiar with. 

Many APIs in the wider tech world have 'official' client libraries available in the major common languages - such as JavaScript, Java, Python, Ruby, Go, Kotlin, Swift, etc. This aids adoption of the API by end users.

Initially I thought this would be something we should produce for our API consumers. However, the more I think about this, the more I'm actually thinking we may **not** actually need client libraries because the type of consumers we are expecting to have are going to be integrating the API into a wide range of primarily _existing_ clinical software.

Also, our API is relatively simple for consumers to use, and a client library may simply not be necessary.

* One thing we could do is ask consumers who develop code for our API in a particular language to 'donate' their client code to the project.

* If we are involved in supporting a consumer to integrate with the API, then we could consider using that as an opportunity to develop a client library in the requisite language.

**Comment by eatyourpeas** [comment]
This issue may never be closed so I will close it now. We have to date build clients in flask and react, as well as built a typescript/react customisable charting library. @chvanlennep has started work on a react native client. As  requests for new clients arrive, we can create issues as we go.
