### ISSUE TITLE
Choice of centiles for growth chart

### ISSUE THREAD

**Issue by statist7** [rcpch/digital-growth-charts-server#21]
The convention for British growth charts is to use the nine-centile format that I proposed in the BMJ (1994), extending from the 0.4th to the 99.6th and defined by a set of z-scores spaced two-thirds of a unit apart. So the nine centiles, 0.4, 2, 9, 25, 50, 75, 91, 98, 99.6, are (except for the 50th) rounded for presentation, and their position on the chart should be defined by the underlying z-score (compactly defined as -4:4*2/3).

Other countries tend to define their chart centiles as whole centiles rather than underlying z-scores, e.g. selecting from the set 1, 3, 5, 10, 25, 50, 75, 90, 95, 97, 99 (an exception is WHO 2006 which uses whole z-scores). For the purposes of internationalization we should make this choice of centiles easy to set up, by defining it as a global preference.

@eatyourpeas I've labelled this mvp as the code change is minor but important.

**Comment by eatyourpeas** [comment]
Can I suggest that this issue is not MVP but actually a desirable future feature? Growth charts currently published in the UK use the 9 centile format and so to my mind this is in effect endorsed by implication. Given the time frame I will reassign this for the moment, but leave open otherwise.

**Comment by pacharanero** [comment]
Fully agree, this isn't an MVP feature

**Comment by eatyourpeas** [comment]
This is now implemented
