### ISSUE TITLE
Mid parental height endpoint doesn't work

### ISSUE THREAD

**Issue by mbarton** [rcpch/digital-growth-charts-server#219]
```
curl -X POST \
  -H 'Content-Type: application/json'
  -d '{"sex":"male","height_paternal": 50,"height_maternal": 50}' \
  http://localhost:8000/utilities/mid-parental-height
Internal Server Error
```

The underlying error is another validation error similar to #213 and #217

```
growth-api-1  |   {'type': 'float_type', 'loc': ('response', 'mid_parental_height_upper_centile_data', 0, 'uk90_preterm', 'male', 'height', 0, 'data', 5, 'y'), 'msg': 'Input should be a valid number', 'input': None}
```

Also seen in the production logs

**Comment by mbarton** [comment]
Looks like `y` is null like in https://github.com/rcpch/digital-growth-charts-server/issues/217

**Comment by eatyourpeas** [comment]
Is this still an issue? 50cm tall is pretty small for any person capable of having children to be. Perhaps we can add some thresholds if they do not exist.

**Comment by mbarton** [comment]
You make a good point, either way the API now returns a response for the example above anyway
