### ISSUE TITLE
LMS method and GAMLSS extensions

### ISSUE THREAD

**Issue by statist7** [rcpch/digital-growth-charts-server#22]
The UK-WHO reference was constructed using the LMS method, which defines the centiles in terms of the median M, coefficient of variation S and skewness L at each age, and summarised as a table with the LMS values in three columns at a series of ages in the rows.

The LMS method is a special case of GAMLSS (generalised models for location, scale and shape), and charts are now being created using more complex GAMLSS models that involve four not three columns of data, where the extra column adjusts for kurtosis (heaviness of tails). 

If the longer term plan is to internationalise the API, we should recognise that this would be a useful extension. It is not too difficult to implement, involving four look-up columns rather than three and a slightly more complex z-score to centile conversion, but I think it's worth considering.

**Comment by eatyourpeas** [comment]
Discussed and felt not practical.
