### ISSUE TITLE
documentation site - latex equation is incorrect

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#221]
Identified now by two users (many thanks to them)
The LATEX representation of the LMS calculation equation is incorrect.
Posting here as the documentation site I don't think has its own repo

**Comment by pacharanero** [comment]
I've fixed this in a branch which was due to be merged into the server repo. Not got around to merging it yet, but it's done.

-------- Original Message --------

**Comment by mbarton** [comment]
I've copied the formula and deployed it separately here https://github.com/rcpch/digital-growth-charts-documentation/pull/109
