### ISSUE TITLE
trisomy-21 AAP

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#227]
Currently T21 (UK) is implemented, but the American Academy of Paediatrics (AAP) also has a reference that is used more widely there and should be included.

questions for @pacharanero 
How should the namespacing be, given that we have already a path: `/trisomy-21/calculation`?

Options:
1. `/trisomy-21-aap/calculation`
2. `/trisomy-21/calculation/aap`
3. `/uk/trisomy-21/calculation` and `/aap/trisomy-21/calculation`
4. something else?

Option 3 is a breaking change for our existing users

**Comment by mbarton** [comment]
I think option 1 is fine
