### ISSUE TITLE
API testing - satisfy Simon and Tim that API returns accurate results

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#37]

**Comment by eatyourpeas** [comment]
The API has been tested extensively by @statist7 with support from @eatyourpeas against LMSGrowth (Excel addin) with agreement to 1e-4 consistently and 1e-5 mostly. It is not clear why closer agreement is not possible, but may related to the data-types used in the original visual basic code base. Results will be reported to 1e-3 in any case. I am therefore closing this issue.
