### ISSUE TITLE
We should be able to produce growth charts for Down's Syndrome

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#41]
This feature is not an MVP feature. But there are standard reference data for growth in Down's Syndrome (Trisomy 21), which we could add to the project in the future. Steps required to do this properly would be:

- [x] obtain accurate Down's Syndrome growth references data from the official source

- [x] convert this from the format it will come in (likely CSV or Excel) into our standard format for LMS growth reference data

- [x] add this reference data to the main references repository (currently this is in the Growth Chart API Server repo, but I'm expecting to move it out into its own repo in the future.

- [x] create a new API endpoint at something like `api/v1/downs-calculations` and configure this in the [server](https://github.com/rcpch/digital-growth-charts-server). Much of the standard centile code will be able to be reused for this, but it may require custom handling hence being at a separate endpoint. Using another endpoint also **completely** removes the possibility of inadvertently requesting Down's references for a non-Down's patient. (for example, if we handled this feature through the main `/calculations/` endpoint and had an additional query string parameter for the reference selection - eventually someone would manage to do it wrong)

- [x] document the new endpoint in the [OpenAPI specification](https://github.com/rcpch/digital-growth-charts-server/blob/alpha/openapi-schema.yml) in the server repo root

- [x] add a view to the Client(s) [flask](https://github.com/rcpch/digital-growth-charts-flask-client) to demonstrate this new feature (likely to be possible to reuse much of the other views)

**Comment by pacharanero** [comment]
@magdaumerska @eatyourpeas as discussed earlier today, this was already in our 'long term' road map but we are kken to keep it moving and it would be an excellent addition to the API in the next 6-12 months

**Comment by pacharanero** [comment]
PR #106 takes us quite a bit closer to this goal

**Comment by eatyourpeas** [comment]
The Turner and T21 references are now in RCPCHGrowth, and can be used to generate measurements from SDS and SDS from measurements. There is also a function to generate plottable chart data of 9 centiles for all the references.
It now needs an endpoint to wire it all up to.
