### ISSUE TITLE
Refactor endpoints for different datasets

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#50]
In future the calculation / calculations endpoint will have less meaning if different datasets are used. This should be refactored now to reflect UK-WHO

**Comment by pacharanero** [comment]
worklist for this
* [x] refactor the API endpoint name (also need to think about `charts` endpoint, which is UK-WHO specific)
* [ ] test in Postman and change Postman collections, upload edited collections
* [ ] refactor in the Flask client
* [ ] test Flask client
* [ ] test React client
* [ ] change the openAPI definition file to reflect changes
* [ ] close issue

**Comment by eatyourpeas** [comment]
@pacharanero I think this issue is now fixed?

**Comment by eatyourpeas** [comment]
(... though I don't think we have the growth references for Hobbits - perhaps @statist7 has a copy? )

**Comment by pacharanero** [comment]
Yes, this refactor was completed a good 6 weeks ago. It's been moved to done but not closed. I think the kanban automation only works the other way around (if you close the issue it's moved to done automatically, not the other way)
