### ISSUE TITLE
Do the thresholds to stop correction (eg 1 year, 2 years) apply from the corrected age or the chronological age?

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#64]
https://github.com/rcpch/digital-growth-charts-server/blob/72e1a5041af9e0ada33a34345e7aa36fcfaa52b9/rcpchgrowth/rcpchgrowth/growth_interpretations.py#L218

**Comment by pacharanero** [comment]
We need this to be decided by the clinical advisors to the project.

**Comment by magdaumerska** [comment]
@pacharanero  - the advisor confirmed it is the corrected age.

**Comment by eatyourpeas** [comment]
The ```corrected_decimal_age``` function contains the following code snippet:
```prematurity = TERM_PREGNANCY_LENGTH_DAYS - pregnancy_length_days

    if pregnancy_length_days >= TERM_LOWER_THRESHOLD_LENGTH_DAYS:
        #term baby
        return uncorrected_age

    elif pregnancy_length_days < EXTREME_PREMATURITY_THRESHOLD_LENGTH_DAYS and uncorrected_age <= 2:
        #correct age for 2 years
        correction_days = prematurity
        edd = birth_date + timedelta(days=correction_days)
        return chronological_decimal_age(edd, observation_date)

    elif (pregnancy_length_days >= EXTREME_PREMATURITY_THRESHOLD_LENGTH_DAYS) and (pregnancy_length_days < TERM_LOWER_THRESHOLD_LENGTH_DAYS) and uncorrected_age <=1:
        #correct age for 1 year
        correction_days = prematurity
        edd = birth_date + timedelta(days=correction_days)
        return chronological_decimal_age(edd, observation_date)
    
    else:
        return uncorrected_age
```

As you can see, the ```uncorrected_age``` is used to decide when the child reaches 1 or 2 y (depending on gestation at delivery) as to whether to correct. As @statist7 says, we remember our birthdays, not our EDDs - the code currently reflects that concept.

**Comment by eatyourpeas** [comment]
Discussion at Project Board 4/9/202
Charlotte Wright and @statist7 conversation - Prof Wright explained that the 1 and 2 year cutoffs for decimal age correction had been purely practical as hard to plot on paper charts, and actually it became of less meaning around the age of 2 years. If measurements can be plotted now with accuracy this removes any need for a threshold for correction and could continue across the life course. It was suggested therefore the api might calculate an SDS for each corrected and each chronological age - therefore providing 2 values per measurement. How these might be plotted therefore offered different possibilties:
1. compare the 2 values and report the lowest
2. compare the 2 values and report the highest
3. plot the measurement that corresponds to the chronological age
4. plot the measurement that corresponds to the corrected age
5. plot both values with a back arrow to join them to denote their relationship as advised in the infants.
As @statist7 also points out. If correction for prematurity is to continue up to the upper threshold of the reference data, might that make the term data obsolete, and should we consider correcting for gestational age even for those babies born at term?

**Comment by statist7** [comment]
For info, Charlotte's exact response to my suggestion (comment to #5 above) was:

> In future we could in principle, but for now it would clash horribly with paper plotted charts  
Also after a few weeks the exact term gestation is often forgotten – could cause problem later  

To paraphrase, the current charts give the centiles for term birth on the y-axis at age 0. If we deprecated the notion of terrmness then the birth centiles would always depend on gestation, and hence would require a chart redesign. So this currently rules it out, though I still think the idea is worth airing more widely.

Her second point strikes me as irrelevant. If the EDD is available for preterm births, as it needs to be if the gestation adjustment is to be continued to adulthood, then why should it not be available for term births?

**Comment by pacharanero** [comment]
Discussed in Sprint Planning 11.09.2020
* The clinical advice is that gestational age correction continues until 1 or 2 years (as appropriate) **corrected age**, thanks @magdaumerska for clarifying this with the advisers.
* This needs to be implemented in code and then we can close this issue. Assigned @eatyourpeas @statist7 @pacharanero
