### ISSUE TITLE
API should only return SDS to 2 decimal places

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#65]
@statist7 suggests that while the unit testing should match LMSGrowth to 10<sup>-5</sup>, the values returned to the end user should be round to 2 decimal places. For the purposes of testing it is easier for the moment not to make this change.

**Comment by statist7** [comment]
Again, not sure if this is the best place to report.

I've now checked the SDS calculations for LMSgrowth, RCPCHgrowth via Google Sheets and my own R code, and the agreement is acceptable.

The screenshot compares the 3 sds values as absolute differences (after excluding the 16 wrong RCPCH values I reported last week). 
![Screenshot 2021-01-29 at 12 16 21](https://user-images.githubusercontent.com/5055653/106274218-d74a0400-622b-11eb-9fc0-e45d47b7e645.png)
The mean agreement is very satisfactory, and the worst cases are all less than 0.005 which guarantees two decimal places of accuracy.

So I'm happy!

**Comment by eatyourpeas** [comment]
This is great @statist7 thank you. We now have 2 branches - one where we correct for decimal age until 1 or 2 y _chronological age_ depending on gestation at birth (which is feeding the google sheets), one where we correct for all gestations including term.  We perhaps need to decide where we take this.
