### ISSUE TITLE
Plot SDS on chart

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#70]
### FROM PROJECT BOARD DISCUSSIONS 2020.09.04
Plotting SDS as well as centiles - need to have red line if < or > 4 SD

**Comment by pacharanero** [comment]
That's an interesting one - makes implementer's job harder if they need to write conditional code to handle the presence of these lines - **but only in certain cases**

**Comment by statist7** [comment]
I rather agree, and suggest this needs rethinking.

**Comment by eatyourpeas** [comment]
This is allied to #66 - discussion here is to propose deprecating returning absolute centile values in favour of centile bands: these would therefore be strings and might include some interpretation (thin/obese etc): discussion still ongoing. It was suggested that +/- 6SD should prompt a warning to consider the measurement may not be accurate. This is somewhat broader than +/-4SD where it was felt some sort of warning/flag might be helpful - hence this suggestion. I will leave this issue open for the time being but for the time being more work is needed conceptually before considering implementation.

**Comment by pacharanero** [comment]
Agreed, this is definitely not yet 'clinically' thought through yet.

I'm not sure I agree with sending **just** centile bands, and would probably try to agree that we send both the centile (as an integer maybe? - no real clinical use for more accuracy than that) AND as a band. And then discussing in the implementation notes the recommendations of the Project Board.

±6SD does sound like a reasonable point to flag a likely error - either in age, gestation, or the actual measurement. And flagging these in the Centile Band field means we don't have to ask implementers to _occasionally_ handle new additional ±4SD or ±6SD lines on the chart plotting data, which would be difficult and likely to be implemented badly.

[In terms of chart plotting, I'm still not entirely convinced that we won't end up with a PNG endpoint - "send me this data plotted correctly on a PNG chart". I know at the start we had dreamed this kind of thing won't be necessary.... they would build lovely vector-based interactive graphs using the measurement and chart-plotting data.... but I think it would make implementation an absolute breeze for some consumers.]

**Comment by eatyourpeas** [comment]
I agree  also we should be cautious about removing the centile value. The board were very clear that reporting exact numbers leads often to confusion between clinicians and patients alike. This discussion should probably continue over at #68 . The implementation in that branch currently leaves the centile values in but adds a separate key:value in the Measurement object called ```centile_band```
I would love to know whether you think we should look this up from YAML? And whether this code belongs within the python package, which is currently where it is.

**Comment by statist7** [comment]
Sending the centile as an integer is sensible for most of the range, but absolutely not below the 1st or above the 99th centile, where one decimal place is needed.

**Comment by eatyourpeas** [comment]
Just to add that this has been dealt with in #76 with fix applied with commit https://github.com/rcpch/digital-growth-charts-server/commit/4af960e99fd926e3e5241b8a2fe0e4b73104a5df

**Comment by eatyourpeas** [comment]
The conversation has drifted into centiles. The issue here is whether SDS charts should be included in MVP. My feeling is they are not in the red book and should be part of a future release. I would like to bundle SDS charts with trend analysis also.
If we all agree I will move this out of MVP? @statist7 @pacharanero I would be grateful if you could let me know where you both stand.

**Comment by pacharanero** [comment]
I am very keen to keep MVP really tight and focused on a genuinely minimum viable product and certainly we shouldn't be implementing stuff that's not currently in the existing charts or the red book. I'd agree this is for a future development roadmap.

**Comment by statist7** [comment]
I agree, not MVP.
