### ISSUE TITLE
Consider deemphasising prescription of colours

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#71]
### FROM PROJECT BOARD DISCUSSIONS 2020.09.04
Discussed at project board. Colours not necessary and do not need prescribing. Change chart to black and white

**Comment by pacharanero** [comment]
Agree that pink and blue is a little bit old-fashioned and not consistent with a modern view of gender, sex, identity, etc. Also just plain unnecessary! Need to ensure that charts are always clearly labelled Male and Female, so the correct references are being used.

**Comment by eatyourpeas** [comment]
This was discussed at Project Board and decision made to de-emphasise colours - leaving it to developers to decide. A comment about it will be made in the documentation. Our current demo clients are black and white. I will close this issue therefore.
