### ISSUE TITLE
Remove BMI charts under 2 years

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#72]
### FROM PROJECT BOARD DISCUSSIONS 2020.09.04
Project board discussion  - length is unreliable under the age of 2 years and therefore while reference data exists, it should not be used.

**Comment by eatyourpeas** [comment]
Not sure how to implement this. Currently BMI is there from 2 weeks to 2 years in UK-WHO, and 1-20 in T21. I think project board are worried about the interpretation of BMI and want it left out of MVP for the moment. I am not sure we whether we should constrain the requests to accept BMI only in >2y, or throttle it further down in the code. And of course the chart package will need updating.

**Comment by pacharanero** [comment]
Perhaps we could set a (possibly temporary) override which filters for 2 weeks - 2 years and returns "Although BMI can be calculated in the UK-WHO references for this age group, it is considered by experts in growth to be potentially misleading and therefore the value is not returned."

And maybe even include a link to this Issue (we could add text from Project board to this issue explaining the decision)

**Comment by pacharanero** [comment]
Discussed as SPM 5.2.21
For re-discussion with senior Project Board members in next couple of weeks

**Comment by eatyourpeas** [comment]
Decision at project board: 11th February 2021 - BMI to be returned down to 2 weeks as per reference data. However, ePCHR should only render BMI from 4y and up
