### ISSUE TITLE
Head circumference SDS returned less accurate than sds for other parameters

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#73]
@statist7 observation that OFC values returned are not as accurate.

**Comment by statist7** [comment]
I've established that head circumference z-score in a preterm infant is fully accurate (i.e. error ~ 1e-7) on the preterm curve, but is much less so once on the WHO curve after 2 weeks corrected age.

I'd like to check the LMS parameters for WHO - please can you tell me where I'll find them on GitHub?

**Comment by statist7** [comment]
I've now found the constants. One immediate realisation is that many of the ages are not accurate. They represent exact months so multiplied by 12 should be an integer, but many are out by ±0.004. So they need recalculating by multiplying by 12, rounding to an integer, and then dividing by 12.

Note this **does not apply** to the early ages, which are in units of weeks. But they too need to be made accurate by following the procedure above with weeks rather than months.

**Comment by statist7** [comment]
Looking at the UK-WHO preterm LMS values for OFC, I see that the first 20 have 5 decimal places for M and 8 for S (and none for L as it is always 1). They correspond to gestation weeks 23 to 42, and they match the precision in the LMSgrowth Excel module. 

However after 42 weeks, corresponding to weeks 2,3,4 then months 1,2,3... for the WHO standard, there are only 2 decimal places for M and 4 for S. However in LMSgrowth there are 4 decimal places for M and 5 for S, so the JSON values are truncated. 

Weight and height have LMS values to the same precision as in LMSgrowth. So this explains the poor level of agreement that we are getting for OFC.

**Comment by pacharanero** [comment]
@statist7 this is good to know - hopefully this will fix the accuracy issue!
@eatyourpeas I would like to help fix this, perhaps is we can pair on it it would be a good way of increasing my familiarity with that area of the code? Thurs/Fri I have availabilty I think.

**Comment by statist7** [comment]
With a bit of luck, recalculating age should improve accuracy across the board.

**Comment by eatyourpeas** [comment]
Sorry to be slow to get back to you - that is interesting. The main tables
are the .json files. I will check if there arent any errors.
https://github.com/rcpch/digital-growth-charts-server/tree/alpha/rcpchgrowth/rcpchgrowth/data_tables
S

**Comment by eatyourpeas** [comment]
Good detective work @statist7 thank you. I will look at this and report back.

**Comment by eatyourpeas** [comment]
@statist7 just looking now at the reference tables I have. The UK_WHO_0_20_Preterm spreadsheet I have has all the datasets stitched together. Here, from 2 weeks to 4 years, M is to 2 dp, S to 4 dp. After this (4-20y) M is 3 dp and S is 5 dp.
I have another reference table (UK_WHO) which runs from 2 weeks to 4 years, where M is to 4 dp and S is to 5dp. Comparing the numbers, apart from the precision, look to be the same. I don't seem to have a sheet of the UK90 data alone from 4-20y, as I do for the WHO, to compare. Would you have that? 
I will update the 2 week to 4y refs in the API with WHO more precise LMS for head circumference. Do I need to make any changes to the 4-20y UK90 numbers too? If so, do you have a reference you could send?

**Comment by statist7** [comment]
The UK-WHO term and preterm spreadsheets include the British 1990 values for age 4-20 years. There are 3dp for M and 5dp for S for OFC in this age range, which match what you already have. So they shouldn't need changing.

**Comment by eatyourpeas** [comment]
I have updated the data tables with increased precision for the WHO OFC data and this generates charts that look similar to the previous - see commit https://github.com/rcpch/digital-growth-charts-server/commit/fc76a7fd5b5534108f42eca73cecd751b759e32b. @pacharanero will create an endpoint for the react app for you to try it out. A separate conversation is needed with regard to decimal age calculation which I will start elsewhere. Just to say though that the Constants.py file contains constants which are only used to identify important thresholds in the datasets - nothing is used here to actually do any calculations.

**Comment by statist7** [comment]
Will my usual client URL catch the latest changes, or should I wait for @pacharanero ?

**Comment by pacharanero** [comment]
I have been trying to set up a new React client deploy for the 'unstable' branch, which allows us to have two sets of software available - the alpha branch (which we try not to break) and the unstable branch (which we deploy latest code to, and which may break occasionally because of this)

The unstable client will be at https://rcpch-dgc-react-client-unstable.azurewebsites.com/ however there has been some kind of Azure related snag to setting this up and it won't work. I'm debugging this at present

**Comment by eatyourpeas** [comment]
I have pushed these new changes to the 'unstable' branch - so let's wait for @pacharanero to work his magic.

**Comment by eatyourpeas** [comment]
This is now resolved. OFC is now accurate to 1e-4.
