### ISSUE TITLE
Could decimal age be made more accurate?

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#74]
Question to @statist7:
Current decimal age calculation works by counting the number of days between two dates and dividing by 365.25 (to account for leap years every 4th year). This is the method used in LMS Growth and Sitar. In fact however as @andrewpalmeruk points out, leap years do not occur on the millenium. FUN FACT: leap years were invented by Julius Caesar in 46 BC. The idea is that it takes 365.25 days for the earth to go round the sun, so to synchronise the solar year with the calendar year, an extra day is added every 4 years. In in actual fact, it takes 365 days, 5 hours, 48 minutes and 46 seconds. Eventually even this small discrepancy would knock our calendar off course. So, leap years occur every four years, but every 100 years we skip a leap year – unless the year is divisible by 400. (more [here](https://www.bbc.co.uk/programmes/articles/16vV1jB2VCLPrkypwV749Jh/everything-you-need-to-know-about-leap-years))
Currently our date calculations do not take this into account.
Perhaps we could consider using the [PyAstronomy](https://pyastronomy.readthedocs.io/en/latest/pyaslDoc/aslDoc/decimalYear.html) package which returns a decimal year for a date. Or one of [these stackoverflow suggestions](https://stackoverflow.com/questions/6451655/how-to-convert-python-datetime-dates-to-decimal-float-years)

**Comment by andrewpalmeruk** [comment]
I think there may be other questions to unpack here. Such as:
1. Since years have differing numbers of seconds in them, should we be using Gregorian years or millisecond years when generating values? I suppose the answer to this comes down to what the LMS charts use, which you’ve mentioned already Simon.
2. What are we using ‘age’ for? I see we’re displaying it on the flask client but what’s the purpose of that in the API? Ie do we need to send back the age of a child when they sent it to us in the first place?

**Comment by eatyourpeas** [comment]
Currently we are using Julian calendar methodology which has the concept of leap years - ie every 4 years is a leap year (366 days), therefore average year length is 365.25. 
The Gregorian calendar (introduced in 1582) is more accurate - it recognised that 365.25 is too short (actual is 365.24217 days), and therefore with the Julian calendar, 3 days are gained every 400 years. To correct the discrepancy the Gregorian calendar concluded that years divisible by 100 would NOT be leap years, but would be if divisible by 400. If I have understood that correctly.
Age is calculated by the API from the dates supplied by the user. We currently return chronological age (years from delivery) and corrected age (if premature - years from expected date of delivery following a 40 week pregnancy). The years are expressed as a decimal using the 4 year rule, but currently do not account for centenaries or quadricentenaries (if that is a word). Mostly because decimal age is not concept widely used outside of growth and endocrinology. 

Either way the main difficulty with either calendar is that the years are not the same length. I suspect the PyAstronomy package is the closest we will get. But the maths in our gold standards (LMSGrowth and Sitar) both use the Julian methodology.

Once again, final arbiter for this I suspect needs to be @statist7

**Comment by statist7** [comment]
This is all getting a bit metaphysical.

I suggest we stick with the Julian calendar of 365.25 days per year ignoring leap centuries, as they are a long time coming. 

And to answer @andrewpalmeruk 's point, the API receives not age but two dates (or three including expected date of delivery). So it makes sense for the API to return age (or two ages if gestation is specified).
