### ISSUE TITLE
Create fictional children to test API

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#86]
Use LMS growth and python RCPCHGrowth to generate some fictional children against which to test API rsults

**Comment by statist7** [comment]
I've created a .csv file with some dummy data in the format required by the flask client.

Currently it is 400 lines long, i.e. 100 x 4 measurements, and is created as follows: 
- birth_date is a random uniform between 2012-01-01 and 2019-01-01
- observation_date is a random uniform number of days later, between 0 and 20 * 365
- gestation_weeks is a random uniform number between 22 and 44
- gestation_days is a random uniform number between 0 and 6
- sex is random binomial male or female
- measurement_method is either weight, height, bmi or ofc
- measurement_value is obtained as a random normal deviate 
-- back-transformed to a centile using the UK-WHO reference in R, preterm for gestation_weeks < 37 or else term
-- and then rounded to respectively 2,1,2,1 decimal places for weight, height, bmi, ofc
-- bmi is then recalculated from weight and height.

Note there are some NA values for ofc beyond 17/18 years. 

This is all coded in R and very easy to change. I suggest we start with this, constructing tests for each row, then if required I can produce a larger file for the final testing.

NB It won't accept a .csv file so I've zipped it.

[csv.csv.zip](https://github.com/rcpch/digital-growth-charts-server/files/5379118/csv.csv.zip)

**Comment by statist7** [comment]
Here's a new version with SDS. Can we discuss this pm?
[RCPCH.csv.zip](https://github.com/rcpch/digital-growth-charts-server/files/5428737/RCPCH.csv.zip)

**Comment by pacharanero** [comment]
Thanks @statist7 that is great and I've been able to make progress on the unit testing
Sorry we didn't end up having the Sprint Planning Meeting yesterday.

(For future reference can we try to use *4-digit dates* in all dates in all documents or resources? Internally we are using ISO8601 dates in the code, which looks like YYYY-MM-DD, with the intention to reduce any ambiguity. I've converted the dates in the CSV you sent, using some RegEx magic - this is just for future reference.)

**Comment by statist7** [comment]
Will do, and sorry I didn’t spot it had changed.

Sent from my iPhone

On 24 Oct 2020, at 12:16, Marcus Baw <notifications@github.com> wrote:

﻿

Thanks @statist7<https://github.com/statist7> that is great and I've been able to make progress on the unit testing
Sorry we didn't end up having the Sprint Planning Meeting yesterday.

(For future reference can we try to use 4-digit dates in all dates in all documents or resources? Internally we are using ISO8601 dates in the code, which looks like YYYY-MM-DD, with the intention to reduce any ambiguity. I've converted the dates in the CSV you sent, using some RegEx magic - this is just for future reference.)

**Comment by pacharanero** [comment]
I've got this plugged in and working now.

I had to remove the 5 test cases which had `"NA"` as either the measurement value or as the SDS. These are presumably to test those situations in which a BMI centile (for example) cannot exist because references don't exist for that age. I think we should probably create manual test cases for all these possible edge cases. It would have been hard to handle those strings and would have needed additional logic.

But with the remainder we have 395 passing test cases, across a wide range of ages, sex, and measurement_type.

Worth noting that they only pass with `ACCURACY = 1e-3` not `1e-4`. At an `ACCURACY` of `1e-4` only about half pass. Is this acceptable?

**Comment by statist7** [comment]
That's excellent news. 

I'm a bit concerned about the `NA` cases, as they will inevitably happen with ages outside the range. The system needs to handle them gracefully.

I wonder why the precision is only `1e-3` - perhaps I've built some imprecision into my code. Do you know if BMI was the culprit, as I have to handle it differently being a calculated variable?

**Comment by pacharanero** [comment]
@statist7 

##`NA`
I will handle the NA cases via separate, manually generated 'edge-case' tests - testing things like:
* invalid input values incl nonsensical ones (like numbers for sex and words for gestation_weeks),
* input values out of sensible range (testing for the right type of Error being raised by the class)
* valid inputs which cannot be calculated (eg preterm BMI) should return 'nil' or equivalent, gracefully

##Precision
When running the tests with the higher precision it's a range of all different types of measurement that fail, not just the BMI ones.. Perhaps a call with us three @statist7 @pacharanero @eatyourpeas together would help in terms of working back through to where the differences occur, and decide if any further optimisations can be made.

**Comment by eatyourpeas** [comment]
These are 92 that failed out of the ~400 tests run.
None are BMI - all a mix of ofc, height and weight. The main thing in common is they are mostly all preterm with some exceptions, and a few with strange gestations (eg 44 weeks) so I will look at the decimal age calculation and see how these are handled. I think correction currently happens below 37 weeks and everything else is considered term. We did discuss this before but I think never agreed a solution. Yes a call is good idea - I can set something up next week if you are free.
[failures.xlsx](https://github.com/rcpch/digital-growth-charts-server/files/5435470/failures.xlsx)

**Comment by eatyourpeas** [comment]
This is the corrected age function. If the gestation entered is >=37 (TERM_LOWER_THRESHOLD_DAYS) no correction is made, so that should prevent correction for post term babies. If that is what we want.
![image](https://user-images.githubusercontent.com/1058647/97114130-8c799700-16e6-11eb-8a59-ae0d5d6a3c29.png)

**Comment by eatyourpeas** [comment]
[failures.xlsx](https://github.com/rcpch/digital-growth-charts-server/files/5435724/failures.xlsx)
Just in follow up - included as a separate sheet are the values that pass 1e-4. All the BMIs are here. No obvious patterns.

**Comment by statist7** [comment]
It's odd that all the BMIs pass, and most of the ofcs. Weight seems to be the worst. BMI is different because I deliberately did not round it, but calculated it from rounded weight and height.

Yes let's meet to discuss. I can do Wednesday after 3pm or Thursday after 4pm, or Friday.

**Comment by pacharanero** [comment]
I can do Thursday or Friday at those times @statist7 . How about Friday afternoon before the other meetings we have (postponed from last Friday) - something like 1pm giving us 2 hours to work on this before the HTN prep call and the SPM

**Comment by statist7** [comment]
1pm Friday is good for me. I'll do some checking against R in the meantime.

**Comment by eatyourpeas** [comment]
I think this issue is now complete. Our troubleshooting has identified that disagreement between R and python is not to do with the randomly generated cases, but to do with the differing implementation of splines. I will close this.
