### ISSUE TITLE
Create Unit tests against fictional random generated children

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#87]
Use LMS growth to produce gold standard values against which to test the API in the RCPCHGrowth package

**Comment by statist7** [comment]
This can be progressed using the file with issue #86.

**Comment by pacharanero** [comment]
We now have hundreds of test data points being fired at the Measurement class in testing. There is always more testing we can add, it will be ongoing. But for now I'm going to close this as we have got to a point where we have got the test suite started and have automated testing on deploy to Azure (via GH)
