### ISSUE TITLE
TestDecimalAge needs to be converted to use PyTest

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#92]
https://github.com/rcpch/digital-growth-charts-server/blob/784816bc32316fd70e661eb54ed76151ce378094/rcpchgrowth/rcpchgrowth/tests/test_dates.py#L6-L6

**Comment by AcidUK** [comment]
I've had a go at refactoring this. I've put in parameterisation for the last two tests from the original file even though they currently only have one test in each. This should allow addition of any further cases in the future. I'm not confident enough to add further test cases myself (yet!)

**Comment by pacharanero** [comment]
Thanks @AcidUK  and I've merged.

For info, there is a small amount of duplication here with a new suite of tests which are being developed in branch `testing-improvements`, but you wouldn't have been able to know that!

For now, more tests is good. We can rationalise them down in the future.

If you fancy doing any more testing, we would like to add some more tests to `/tests/test_measurement_class.py` to test the inputs of the class at instantiation with various valid and invalid inputs. We have some existing tests that do this, we'd like to extend this using that pattern

IMPORTANT: All of the contents of `rcpchgrowth/rcpchgrowth` are being refactored out into a new repository because it is being reborn as a standalone Python package on PyPi. So all new tests for that bit will be in https://github.com/rcpch/rcpchgrowth-python

Thanks again and I'll close this issue.
