### ISSUE TITLE
confusion re fictional_child_data.py and fictional_children.py

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#93]
@eatyourpeas we had a regression noticed today which I think comes from the change to the new `fictional_children.py` controller. I think this came in with the plottable_child_data PR
The endpoint for create_fictional_child_measurements was failing tests in Postman, and when traced back it's because the `fictional_child_data.py` file had been removed from the __init__.py
I've added it back, but I think we need to work out which one of these we're keeping.

**Comment by eatyourpeas** [comment]
I am not entirely sure we really need the fictional_child end point any more. I think it is a nice feature to have for users wanting to create dummy data, but certainly not essential. I will reclassify this as a desirable feature for the moment. If you agree, I think we should deprecate what is there for the moment.

**Comment by pacharanero** [comment]
Yes I do agree it's not a huge priority.

If we remove it we should supply implementers with an alternative source of realistic test data, because producing plausible test data is much harder for non-clinicians than we think it is. I struggle sometimes to try to come up with really plausible cases (not just for growth but for anything when I'm testing stuff)

An alternative could be simply a JSON file.

Or we could just use Fictional Child. Maybe a re-name though. I've always thought 'Fictional' sounds unreliable somehow. 'Test Data Generator' or something?

**Comment by BB-1313** [comment]
I can see you're both busy this weekend!  If it is just a set of realistic test data why not just acquire it from a clinical data set, I'm sure I could get a dataset of pretty much any specificiation from our EPR?
If it needs to be a varying sample for test purposes tihi could be randomly selected from a larger fixed sample?
Would that work?

**Comment by eatyourpeas** [comment]
The nice thing about growth data is that it is very easy to autogenerate and removes any of the confidentiality issues. I created a function in the early days which took two dates, a sex and gestation, a starting SDS, a measurement method and a drift constant, and generated a 'fictional child' growing across a timespan. @statist7 has written code in R which generates a random set of 400+ children to test the API with ('fictional children') and I think some time back I tried something similar. Ultimately we just need @statist7's for the moment to test the API with each deploy. When we start writing code which looks at growth velocity/acceleration and so on we will need datasets of multiple growth data of individual children to test against so I will revisit the fictional child at that point. As @pacharanero says, we could probably pick a better name. My feeling is we could deprecate the endpoint for the moment - it would be quick to rewrite again if we needed it.

**Comment by BB-1313** [comment]
Yes I saw that, I was thinking more at some stage some real data with errors might be worth throwing at it!
Confidentiality shouldn't be an issue especially if it's just the individual observations.
Probably for later when you have an MVP.

**Comment by eatyourpeas** [comment]
@pacharanero has plans to throw all kinds of crazy data at it, including letters and @$*! to make sure it handles it all gracefully. I have noticed actually that if you put bmi uppercase rather than lowercase it breaks with no sensible error so that definitely needs fixing. @pacharanero do you know anything about Enums in python? That is what I would do in JS/Android/Swift. Then we could throw a TypeError or a ValueError. I will create a new issue about that.
