### ISSUE TITLE
We should Dockerise the server to simplify setup for devs

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-server#96]
@pacharanero has started work on this with commit https://github.com/rcpch/digital-growth-charts-server/commit/d3a53230011074b28e7146772693ea224caf2829

**Comment by eatyourpeas** [comment]
I would like to learn more about dockerising. Perhaps we could pair on this one @pacharanero ?

**Comment by pacharanero** [comment]
Definitely. Let me know when is good for you.

**Comment by pacharanero** [comment]
I've created a Dockerfile and some scripts `s/start-docker` and `s/rebuild-docker` which assist in the creation of the image and the container. Inside the container should be the correct Python version, dependencies, and a running application server. 

The main use of this is to help standardise and simplify the setup process for those developing the API code or running locally for testing. The API should be present on `localhost:5000` although this can be changed easily by amending the docker commands in the startup script to map the exposed port to a different port. (Note that the `EXPOSE` directive in the Dockerfile does **not** actually change the exposed port, it's more for documentative purposes)
